name: Main
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.3.0
      with:
        node-version: "14"
        cache: 'npm'
    - name: Install npm v7
      run: npm install -g npm@7.x.x
    - uses: actions/cache@v2.1.6
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
    - name: install
      run: npm -v; npm ci
    - name: typecheck
      run: npm run type-check
    - name: lint
      run: npm run lint
    - name: build
      run: npm run build
